{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 33,
   "id": "0cff1900-5767-46ec-8d9a-848195344096",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "' 2. Create a dual-axis chart comparing the average installs and revenue for free vs. paid apps within the top 3 app categories. \\nApply filters to exclude apps with fewer than 10,000 installs and revenue below $10,000 and android version should be more than 4.0 as well as size should be more than 15M and content rating should be Everyone and app name should not have more than 30 characters including space and special character .\\nThis graph should work only between 1 PM IST to 2 PM IST apart from that time we should not show this graph in dashboard itself.'"
      ]
     },
     "execution_count": 33,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "''' 2. Create a dual-axis chart comparing the average installs and revenue for free vs. paid apps within the top 3 app categories. \n",
    "Apply filters to exclude apps with fewer than 10,000 installs and revenue below $10,000 and android version should be more than 4.0 as well as size should be more than 15M and content rating should be Everyone and app name should not have more than 30 characters including space and special character .\n",
    "This graph should work only between 1 PM IST to 2 PM IST apart from that time we should not show this graph in dashboard itself.'''"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 34,
   "id": "f548b5d3-92cf-439f-9d5e-786c484ab348",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (2.2.3)\n",
      "Requirement already satisfied: numpy in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (2.2.6)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in e:\\data analyst intern tasks\\jupyter\\venv\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install pandas numpy"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 35,
   "id": "0a77a4c9-eb80-4ee3-972c-c7858e8d6fb0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Name: matplotlib\n",
      "Version: 3.10.3\n",
      "Summary: Python plotting package\n",
      "Home-page: https://matplotlib.org\n",
      "Author: John D. Hunter, Michael Droettboom\n",
      "Author-email: Unknown <matplotlib-users@python.org>\n",
      "License: License agreement for matplotlib versions 1.3.0 and later\n",
      " =========================================================\n",
      "\n",
      " 1. This LICENSE AGREEMENT is between the Matplotlib Development Team\n",
      " (\"MDT\"), and the Individual or Organization (\"Licensee\") accessing and\n",
      " otherwise using matplotlib software in source or binary form and its\n",
      " associated documentation.\n",
      "\n",
      " 2. Subject to the terms and conditions of this License Agreement, MDT\n",
      " hereby grants Licensee a nonexclusive, royalty-free, world-wide license\n",
      " to reproduce, analyze, test, perform and/or display publicly, prepare\n",
      " derivative works, distribute, and otherwise use matplotlib\n",
      " alone or in any derivative version, provided, however, that MDT's\n",
      " License Agreement and MDT's notice of copyright, i.e., \"Copyright (c)\n",
      " 2012- Matplotlib Development Team; All Rights Reserved\" are retained in\n",
      " matplotlib  alone or in any derivative version prepared by\n",
      " Licensee.\n",
      "\n",
      " 3. In the event Licensee prepares a derivative work that is based on or\n",
      " incorporates matplotlib or any part thereof, and wants to\n",
      " make the derivative work available to others as provided herein, then\n",
      " Licensee hereby agrees to include in any such work a brief summary of\n",
      " the changes made to matplotlib .\n",
      "\n",
      " 4. MDT is making matplotlib available to Licensee on an \"AS\n",
      " IS\" basis.  MDT MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR\n",
      " IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, MDT MAKES NO AND\n",
      " DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS\n",
      " FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB\n",
      " WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.\n",
      "\n",
      " 5. MDT SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB\n",
      "  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR\n",
      " LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING\n",
      " MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF\n",
      " THE POSSIBILITY THEREOF.\n",
      "\n",
      " 6. This License Agreement will automatically terminate upon a material\n",
      " breach of its terms and conditions.\n",
      "\n",
      " 7. Nothing in this License Agreement shall be deemed to create any\n",
      " relationship of agency, partnership, or joint venture between MDT and\n",
      " Licensee.  This License Agreement does not grant permission to use MDT\n",
      " trademarks or trade name in a trademark sense to endorse or promote\n",
      " products or services of Licensee, or any third party.\n",
      "\n",
      " 8. By copying, installing or otherwise using matplotlib ,\n",
      " Licensee agrees to be bound by the terms and conditions of this License\n",
      " Agreement.\n",
      "\n",
      " License agreement for matplotlib versions prior to 1.3.0\n",
      " ========================================================\n",
      "\n",
      " 1. This LICENSE AGREEMENT is between John D. Hunter (\"JDH\"), and the\n",
      " Individual or Organization (\"Licensee\") accessing and otherwise using\n",
      " matplotlib software in source or binary form and its associated\n",
      " documentation.\n",
      "\n",
      " 2. Subject to the terms and conditions of this License Agreement, JDH\n",
      " hereby grants Licensee a nonexclusive, royalty-free, world-wide license\n",
      " to reproduce, analyze, test, perform and/or display publicly, prepare\n",
      " derivative works, distribute, and otherwise use matplotlib\n",
      " alone or in any derivative version, provided, however, that JDH's\n",
      " License Agreement and JDH's notice of copyright, i.e., \"Copyright (c)\n",
      " 2002-2011 John D. Hunter; All Rights Reserved\" are retained in\n",
      " matplotlib  alone or in any derivative version prepared by\n",
      " Licensee.\n",
      "\n",
      " 3. In the event Licensee prepares a derivative work that is based on or\n",
      " incorporates matplotlib  or any part thereof, and wants to\n",
      " make the derivative work available to others as provided herein, then\n",
      " Licensee hereby agrees to include in any such work a brief summary of\n",
      " the changes made to matplotlib.\n",
      "\n",
      " 4. JDH is making matplotlib  available to Licensee on an \"AS\n",
      " IS\" basis.  JDH MAKES NO REPRESENTATIONS OR WARRANTIES, EXPRESS OR\n",
      " IMPLIED.  BY WAY OF EXAMPLE, BUT NOT LIMITATION, JDH MAKES NO AND\n",
      " DISCLAIMS ANY REPRESENTATION OR WARRANTY OF MERCHANTABILITY OR FITNESS\n",
      " FOR ANY PARTICULAR PURPOSE OR THAT THE USE OF MATPLOTLIB\n",
      " WILL NOT INFRINGE ANY THIRD PARTY RIGHTS.\n",
      "\n",
      " 5. JDH SHALL NOT BE LIABLE TO LICENSEE OR ANY OTHER USERS OF MATPLOTLIB\n",
      "  FOR ANY INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES OR\n",
      " LOSS AS A RESULT OF MODIFYING, DISTRIBUTING, OR OTHERWISE USING\n",
      " MATPLOTLIB , OR ANY DERIVATIVE THEREOF, EVEN IF ADVISED OF\n",
      " THE POSSIBILITY THEREOF.\n",
      "\n",
      " 6. This License Agreement will automatically terminate upon a material\n",
      " breach of its terms and conditions.\n",
      "\n",
      " 7. Nothing in this License Agreement shall be deemed to create any\n",
      " relationship of agency, partnership, or joint venture between JDH and\n",
      " Licensee.  This License Agreement does not grant permission to use JDH\n",
      " trademarks or trade name in a trademark sense to endorse or promote\n",
      " products or services of Licensee, or any third party.\n",
      "\n",
      " 8. By copying, installing or otherwise using matplotlib,\n",
      " Licensee agrees to be bound by the terms and conditions of this License\n",
      " Agreement.\n",
      "Location: E:\\Data Analyst Intern Tasks\\Jupyter\\venv\\Lib\\site-packages\n",
      "Requires: contourpy, cycler, fonttools, kiwisolver, numpy, packaging, pillow, pyparsing, python-dateutil\n",
      "Required-by: seaborn, wordcloud\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip show matplotlib"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 36,
   "id": "57a83d72-ad44-496d-8fbe-b6b6c25e047f",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "from datetime import datetime, time\n",
    "import pytz\n",
    "import numpy as np\n",
    "%matplotlib inline"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 37,
   "id": "b434eef9-78dc-434c-bd00-fd88b5ce46e9",
   "metadata": {},
   "outputs": [],
   "source": [
    "apps_df = pd.read_csv(\"E:/Data Analyst Intern Tasks/Jupyter/Cleaned Datasets/Cleaned_GooglePlaystore.csv\")\n",
    "reviews_df = pd.read_csv(\"E:/Data Analyst Intern Tasks/Jupyter/Cleaned Datasets/Cleaned_UserReviews.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 38,
   "id": "d4f6d0fa-4cdf-4ec3-9a8f-da1c2a8f9a36",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>App</th>\n",
       "      <th>Category</th>\n",
       "      <th>Rating</th>\n",
       "      <th>Reviews</th>\n",
       "      <th>Size</th>\n",
       "      <th>Installs</th>\n",
       "      <th>Type</th>\n",
       "      <th>Price</th>\n",
       "      <th>Content Rating</th>\n",
       "      <th>Genres</th>\n",
       "      <th>Last Updated</th>\n",
       "      <th>Current Ver</th>\n",
       "      <th>Android Ver</th>\n",
       "      <th>Log_Installs</th>\n",
       "      <th>Log_Reviews</th>\n",
       "      <th>Rating_Group</th>\n",
       "      <th>Revenue</th>\n",
       "      <th>Year</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>Photo Editor &amp; Candy Camera &amp; Grid &amp; ScrapBook</td>\n",
       "      <td>ART_AND_DESIGN</td>\n",
       "      <td>4.1</td>\n",
       "      <td>159</td>\n",
       "      <td>19.0</td>\n",
       "      <td>10000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Art &amp; Design</td>\n",
       "      <td>2018-01-07</td>\n",
       "      <td>1.0.0</td>\n",
       "      <td>4.0.3 and up</td>\n",
       "      <td>9.210340</td>\n",
       "      <td>5.068904</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>Coloring book moana</td>\n",
       "      <td>ART_AND_DESIGN</td>\n",
       "      <td>3.9</td>\n",
       "      <td>967</td>\n",
       "      <td>14.0</td>\n",
       "      <td>500000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Art &amp; Design;Pretend Play</td>\n",
       "      <td>2018-01-15</td>\n",
       "      <td>2.0.0</td>\n",
       "      <td>4.0.3 and up</td>\n",
       "      <td>13.122363</td>\n",
       "      <td>6.874198</td>\n",
       "      <td>Above average</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>U Launcher Lite – FREE Live Cool Themes, Hide ...</td>\n",
       "      <td>ART_AND_DESIGN</td>\n",
       "      <td>4.7</td>\n",
       "      <td>87510</td>\n",
       "      <td>8.7</td>\n",
       "      <td>5000000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Art &amp; Design</td>\n",
       "      <td>2018-08-01</td>\n",
       "      <td>1.2.4</td>\n",
       "      <td>4.0.3 and up</td>\n",
       "      <td>15.424948</td>\n",
       "      <td>11.379508</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>Sketch - Draw &amp; Paint</td>\n",
       "      <td>ART_AND_DESIGN</td>\n",
       "      <td>4.5</td>\n",
       "      <td>215644</td>\n",
       "      <td>25.0</td>\n",
       "      <td>50000000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Teen</td>\n",
       "      <td>Art &amp; Design</td>\n",
       "      <td>2018-06-08</td>\n",
       "      <td>Varies with device</td>\n",
       "      <td>4.2 and up</td>\n",
       "      <td>17.727534</td>\n",
       "      <td>12.281384</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>Pixel Draw - Number Art Coloring Book</td>\n",
       "      <td>ART_AND_DESIGN</td>\n",
       "      <td>4.3</td>\n",
       "      <td>967</td>\n",
       "      <td>2.8</td>\n",
       "      <td>100000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Art &amp; Design;Creativity</td>\n",
       "      <td>2018-06-20</td>\n",
       "      <td>1.1</td>\n",
       "      <td>4.4 and up</td>\n",
       "      <td>11.512925</td>\n",
       "      <td>6.874198</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8191</th>\n",
       "      <td>FR Calculator</td>\n",
       "      <td>FAMILY</td>\n",
       "      <td>4.0</td>\n",
       "      <td>7</td>\n",
       "      <td>2.6</td>\n",
       "      <td>500</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Education</td>\n",
       "      <td>2017-06-18</td>\n",
       "      <td>1.0.0</td>\n",
       "      <td>4.1 and up</td>\n",
       "      <td>6.214608</td>\n",
       "      <td>1.945910</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2017</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8192</th>\n",
       "      <td>Sya9a Maroc - FR</td>\n",
       "      <td>FAMILY</td>\n",
       "      <td>4.5</td>\n",
       "      <td>38</td>\n",
       "      <td>53.0</td>\n",
       "      <td>5000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Education</td>\n",
       "      <td>2017-07-25</td>\n",
       "      <td>1.48</td>\n",
       "      <td>4.1 and up</td>\n",
       "      <td>8.517193</td>\n",
       "      <td>3.637586</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2017</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8193</th>\n",
       "      <td>Fr. Mike Schmitz Audio Teachings</td>\n",
       "      <td>FAMILY</td>\n",
       "      <td>5.0</td>\n",
       "      <td>4</td>\n",
       "      <td>3.6</td>\n",
       "      <td>100</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Education</td>\n",
       "      <td>2018-07-06</td>\n",
       "      <td>1</td>\n",
       "      <td>4.1 and up</td>\n",
       "      <td>4.605170</td>\n",
       "      <td>1.386294</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8194</th>\n",
       "      <td>The SCP Foundation DB fr nn5n</td>\n",
       "      <td>BOOKS_AND_REFERENCE</td>\n",
       "      <td>4.5</td>\n",
       "      <td>114</td>\n",
       "      <td>NaN</td>\n",
       "      <td>1000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Mature 17+</td>\n",
       "      <td>Books &amp; Reference</td>\n",
       "      <td>2015-01-19</td>\n",
       "      <td>Varies with device</td>\n",
       "      <td>Varies with device</td>\n",
       "      <td>6.907755</td>\n",
       "      <td>4.736198</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2015</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8195</th>\n",
       "      <td>iHoroscope - 2018 Daily Horoscope &amp; Astrology</td>\n",
       "      <td>LIFESTYLE</td>\n",
       "      <td>4.5</td>\n",
       "      <td>398307</td>\n",
       "      <td>19.0</td>\n",
       "      <td>10000000</td>\n",
       "      <td>Free</td>\n",
       "      <td>0.0</td>\n",
       "      <td>Everyone</td>\n",
       "      <td>Lifestyle</td>\n",
       "      <td>2018-07-25</td>\n",
       "      <td>Varies with device</td>\n",
       "      <td>Varies with device</td>\n",
       "      <td>16.118096</td>\n",
       "      <td>12.894978</td>\n",
       "      <td>Top rated app</td>\n",
       "      <td>0.0</td>\n",
       "      <td>2018</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>8196 rows × 18 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "                                                    App             Category  \\\n",
       "0        Photo Editor & Candy Camera & Grid & ScrapBook       ART_AND_DESIGN   \n",
       "1                                   Coloring book moana       ART_AND_DESIGN   \n",
       "2     U Launcher Lite – FREE Live Cool Themes, Hide ...       ART_AND_DESIGN   \n",
       "3                                 Sketch - Draw & Paint       ART_AND_DESIGN   \n",
       "4                 Pixel Draw - Number Art Coloring Book       ART_AND_DESIGN   \n",
       "...                                                 ...                  ...   \n",
       "8191                                      FR Calculator               FAMILY   \n",
       "8192                                   Sya9a Maroc - FR               FAMILY   \n",
       "8193                   Fr. Mike Schmitz Audio Teachings               FAMILY   \n",
       "8194                      The SCP Foundation DB fr nn5n  BOOKS_AND_REFERENCE   \n",
       "8195      iHoroscope - 2018 Daily Horoscope & Astrology            LIFESTYLE   \n",
       "\n",
       "      Rating  Reviews  Size  Installs  Type  Price Content Rating  \\\n",
       "0        4.1      159  19.0     10000  Free    0.0       Everyone   \n",
       "1        3.9      967  14.0    500000  Free    0.0       Everyone   \n",
       "2        4.7    87510   8.7   5000000  Free    0.0       Everyone   \n",
       "3        4.5   215644  25.0  50000000  Free    0.0           Teen   \n",
       "4        4.3      967   2.8    100000  Free    0.0       Everyone   \n",
       "...      ...      ...   ...       ...   ...    ...            ...   \n",
       "8191     4.0        7   2.6       500  Free    0.0       Everyone   \n",
       "8192     4.5       38  53.0      5000  Free    0.0       Everyone   \n",
       "8193     5.0        4   3.6       100  Free    0.0       Everyone   \n",
       "8194     4.5      114   NaN      1000  Free    0.0     Mature 17+   \n",
       "8195     4.5   398307  19.0  10000000  Free    0.0       Everyone   \n",
       "\n",
       "                         Genres Last Updated         Current Ver  \\\n",
       "0                  Art & Design   2018-01-07               1.0.0   \n",
       "1     Art & Design;Pretend Play   2018-01-15               2.0.0   \n",
       "2                  Art & Design   2018-08-01               1.2.4   \n",
       "3                  Art & Design   2018-06-08  Varies with device   \n",
       "4       Art & Design;Creativity   2018-06-20                 1.1   \n",
       "...                         ...          ...                 ...   \n",
       "8191                  Education   2017-06-18               1.0.0   \n",
       "8192                  Education   2017-07-25                1.48   \n",
       "8193                  Education   2018-07-06                   1   \n",
       "8194          Books & Reference   2015-01-19  Varies with device   \n",
       "8195                  Lifestyle   2018-07-25  Varies with device   \n",
       "\n",
       "             Android Ver  Log_Installs  Log_Reviews   Rating_Group  Revenue  \\\n",
       "0           4.0.3 and up      9.210340     5.068904  Top rated app      0.0   \n",
       "1           4.0.3 and up     13.122363     6.874198  Above average      0.0   \n",
       "2           4.0.3 and up     15.424948    11.379508  Top rated app      0.0   \n",
       "3             4.2 and up     17.727534    12.281384  Top rated app      0.0   \n",
       "4             4.4 and up     11.512925     6.874198  Top rated app      0.0   \n",
       "...                  ...           ...          ...            ...      ...   \n",
       "8191          4.1 and up      6.214608     1.945910  Top rated app      0.0   \n",
       "8192          4.1 and up      8.517193     3.637586  Top rated app      0.0   \n",
       "8193          4.1 and up      4.605170     1.386294  Top rated app      0.0   \n",
       "8194  Varies with device      6.907755     4.736198  Top rated app      0.0   \n",
       "8195  Varies with device     16.118096    12.894978  Top rated app      0.0   \n",
       "\n",
       "      Year  \n",
       "0     2018  \n",
       "1     2018  \n",
       "2     2018  \n",
       "3     2018  \n",
       "4     2018  \n",
       "...    ...  \n",
       "8191  2017  \n",
       "8192  2017  \n",
       "8193  2018  \n",
       "8194  2015  \n",
       "8195  2018  \n",
       "\n",
       "[8196 rows x 18 columns]"
      ]
     },
     "execution_count": 38,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "apps_df = apps_df.loc[:, ~apps_df.columns.str.contains('^Unnamed')]\n",
    "apps_df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 39,
   "id": "e33947dd-f562-4da0-a395-9495d5be1ce8",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>App</th>\n",
       "      <th>Translated_Review</th>\n",
       "      <th>Sentiment</th>\n",
       "      <th>Sentiment_Polarity</th>\n",
       "      <th>Sentiment_Subjectivity</th>\n",
       "      <th>Sentiment_Score</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10 Best Foods for You</td>\n",
       "      <td>I like eat delicious food. That's I'm cooking ...</td>\n",
       "      <td>Positive</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.533333</td>\n",
       "      <td>0.9531</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>10 Best Foods for You</td>\n",
       "      <td>This help eating healthy exercise regular basis</td>\n",
       "      <td>Positive</td>\n",
       "      <td>0.25</td>\n",
       "      <td>0.288462</td>\n",
       "      <td>0.6597</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>10 Best Foods for You</td>\n",
       "      <td>Works great especially going grocery store</td>\n",
       "      <td>Positive</td>\n",
       "      <td>0.40</td>\n",
       "      <td>0.875000</td>\n",
       "      <td>0.6249</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>10 Best Foods for You</td>\n",
       "      <td>Best idea us</td>\n",
       "      <td>Positive</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.300000</td>\n",
       "      <td>0.6369</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>10 Best Foods for You</td>\n",
       "      <td>Best way</td>\n",
       "      <td>Positive</td>\n",
       "      <td>1.00</td>\n",
       "      <td>0.300000</td>\n",
       "      <td>0.6369</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                     App                                  Translated_Review  \\\n",
       "0  10 Best Foods for You  I like eat delicious food. That's I'm cooking ...   \n",
       "1  10 Best Foods for You    This help eating healthy exercise regular basis   \n",
       "2  10 Best Foods for You         Works great especially going grocery store   \n",
       "3  10 Best Foods for You                                       Best idea us   \n",
       "4  10 Best Foods for You                                           Best way   \n",
       "\n",
       "  Sentiment  Sentiment_Polarity  Sentiment_Subjectivity  Sentiment_Score  \n",
       "0  Positive                1.00                0.533333           0.9531  \n",
       "1  Positive                0.25                0.288462           0.6597  \n",
       "2  Positive                0.40                0.875000           0.6249  \n",
       "3  Positive                1.00                0.300000           0.6369  \n",
       "4  Positive                1.00                0.300000           0.6369  "
      ]
     },
     "execution_count": 39,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reviews_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "id": "fbdd208a-1b5e-4080-9111-db319108e6c0",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Data Cleaning\n",
    "\n",
    "apps_df = apps_df.dropna(subset=['Rating'])\n",
    "for column in apps_df.columns:\n",
    "    apps_df[column].fillna(apps_df[column].mode()[0])\n",
    "apps_df.drop_duplicates   \n",
    "apps_df = apps_df[apps_df['Rating']<=5]\n",
    "reviews_df.dropna(subset=['Translated_Review'],inplace=True)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 41,
   "id": "782e8cb5-e32d-4450-9494-a4a3883c2f24",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Installs dtype before conversion: int64\n",
      "Price dtype before conversion: float64\n",
      "Installs column is already numeric\n",
      "Price column is already numeric\n"
     ]
    }
   ],
   "source": [
    "# First check the current data type\n",
    "print(f\"Installs dtype before conversion: {apps_df['Installs'].dtype}\")\n",
    "print(f\"Price dtype before conversion: {apps_df['Price'].dtype}\")\n",
    "\n",
    "# Convert only if the column contains strings\n",
    "if apps_df['Installs'].dtype == 'object':\n",
    "    apps_df['Installs'] = apps_df['Installs'].str.replace('[+,]', '', regex=True).astype(int)\n",
    "else:\n",
    "    print(\"Installs column is already numeric\")\n",
    "\n",
    "if apps_df['Price'].dtype == 'object':\n",
    "    apps_df['Price'] = apps_df['Price'].str.replace('$', '', regex=False).astype(float)\n",
    "else:\n",
    "    print(\"Price column is already numeric\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "878c3894-699a-4a35-a86a-da6379f96af3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "\n",
      "After conversion:\n",
      "Installs dtype: int64\n",
      "Price dtype: float64\n"
     ]
    }
   ],
   "source": [
    "def clean_installs(val):\n",
    "    if isinstance(val, str):\n",
    "        return int(val.replace(',', '').replace('+', ''))\n",
    "    return val\n",
    "\n",
    "def clean_price(val):\n",
    "    if isinstance(val, str):\n",
    "        return float(val.replace('$', ''))\n",
    "    return val\n",
    "\n",
    "apps_df['Installs'] = apps_df['Installs'].apply(clean_installs)\n",
    "apps_df['Price'] = apps_df['Price'].apply(clean_price)\n",
    "\n",
    "# Verify conversion\n",
    "print(\"\\nAfter conversion:\")\n",
    "print(f\"Installs dtype: {apps_df['Installs'].dtype}\")\n",
    "print(f\"Price dtype: {apps_df['Price'].dtype}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "d530e3e1-8585-4727-9e51-54dc9143f668",
   "metadata": {},
   "outputs": [],
   "source": [
    "# For missing Android versions, we can use a placeholder like \"Not specified\"\n",
    "apps_df['Android Ver'] = apps_df['Android Ver'].fillna('Not specified')\n",
    "\n",
    "# For missing Current Ver, we can either drop these rows or fill with a placeholder\n",
    "apps_df['Current Ver'] = apps_df['Current Ver'].fillna('Not specified')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 44,
   "id": "48463dc0-be35-4d2a-bd4f-ac166ff43cec",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "App                object\n",
       "Category           object\n",
       "Rating            float64\n",
       "Reviews             int64\n",
       "Size              float64\n",
       "Installs            int64\n",
       "Type               object\n",
       "Price             float64\n",
       "Content Rating     object\n",
       "Genres             object\n",
       "Last Updated       object\n",
       "Current Ver        object\n",
       "Android Ver        object\n",
       "Log_Installs      float64\n",
       "Log_Reviews       float64\n",
       "Rating_Group       object\n",
       "Revenue           float64\n",
       "Year                int64\n",
       "dtype: object"
      ]
     },
     "execution_count": 44,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "apps_df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 45,
   "id": "391ea509-b9c8-4784-9037-abc146dea3ad",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "App                  0\n",
       "Category             0\n",
       "Rating               0\n",
       "Reviews              0\n",
       "Size              1425\n",
       "Installs             0\n",
       "Type                 0\n",
       "Price                0\n",
       "Content Rating       0\n",
       "Genres               0\n",
       "Last Updated         0\n",
       "Current Ver          0\n",
       "Android Ver          0\n",
       "Log_Installs         0\n",
       "Log_Reviews          0\n",
       "Rating_Group         0\n",
       "Revenue              0\n",
       "Year                 0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 45,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "apps_df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 46,
   "id": "5bfa3892-c379-4248-b7bf-ac8ed9ce1d2a",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "App                        object\n",
       "Translated_Review          object\n",
       "Sentiment                  object\n",
       "Sentiment_Polarity        float64\n",
       "Sentiment_Subjectivity    float64\n",
       "Sentiment_Score           float64\n",
       "dtype: object"
      ]
     },
     "execution_count": 46,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reviews_df.dtypes"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 47,
   "id": "46ad5ec1-60aa-4b19-963d-6be18ab02a81",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "App                       0\n",
       "Translated_Review         0\n",
       "Sentiment                 0\n",
       "Sentiment_Polarity        0\n",
       "Sentiment_Subjectivity    0\n",
       "Sentiment_Score           0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 47,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reviews_df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 48,
   "id": "4b590946-63fb-424b-bd5c-46d1104a747c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['App', 'Category', 'Rating', 'Reviews', 'Size', 'Installs', 'Type',\n",
       "       'Price', 'Content Rating', 'Genres', 'Last Updated', 'Current Ver',\n",
       "       'Android Ver', 'Log_Installs', 'Log_Reviews', 'Rating_Group', 'Revenue',\n",
       "       'Year'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 48,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "apps_df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "id": "3cbf5a19-e3cd-42f4-b54d-db5d05fc76fc",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['App', 'Translated_Review', 'Sentiment', 'Sentiment_Polarity',\n",
       "       'Sentiment_Subjectivity', 'Sentiment_Score'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "reviews_df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e3482716-1186-4405-8b3b-f60e33e014cf",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "id": "84f1fd7e-2b5b-46af-9fa8-a80b6497014b",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from tkinter import ttk\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg\n",
    "from matplotlib.ticker import FuncFormatter\n",
    "import matplotlib.font_manager as fm\n",
    "import datetime\n",
    "from matplotlib.patches import Patch"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 51,
   "id": "1c712dc9-976f-4867-9f45-a791d32384b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "apps_df['Installs'] = apps_df['Installs'].astype(str).str.replace(',', '').astype(int)\n",
    "apps_df['Revenue'] = apps_df['Revenue'].replace('[\\\\$,]', '', regex=True).astype(float)\n",
    "apps_df['Size'] = apps_df['Size'].replace('M', '', regex=True).astype(float)\n",
    "apps_df['Android Ver'] = apps_df['Android Ver'].astype(str).str.extract(r'(\\d+\\.?\\d*)')[0].astype(float)\n",
    "apps_df['App Length'] = apps_df['App'].astype(str).str.len()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 52,
   "id": "fd14134d-891d-4027-8716-8c4c22be1717",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Apply filters\n",
    "filtered_df = apps_df[\n",
    "    (apps_df['Installs'] >= 10000) &\n",
    "    (apps_df['Revenue'] >= 10000) &\n",
    "    (apps_df['Android Ver'] > 4.0) &\n",
    "    (apps_df['Size'] > 15) &\n",
    "    (apps_df['Content Rating'] == 'Everyone') &\n",
    "    (apps_df['App Length'] <= 30)\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 53,
   "id": "3ce76a9e-2f65-4661-90f9-1538f0ead705",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Determine top 3 categories by number of apps after filtering\n",
    "top_categories = filtered_df['Category'].value_counts().nlargest(3).index.tolist()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 54,
   "id": "b7e2e6e0-ef9b-4730-a6bb-5fb954250714",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Filter to only top 3 categories\n",
    "filtered_df = filtered_df[filtered_df['Category'].isin(top_categories)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 55,
   "id": "9a29b9d9-90e9-4d43-8cbb-26f82154c27e",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Get current time in IST\n",
    "from datetime import datetime, time\n",
    "import pytz\n",
    "india_time = datetime.now(pytz.timezone(\"Asia/Kolkata\")).time()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 56,
   "id": "9e2777ab-f9fd-49b3-b454-f8106381fc7d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Allowed window: 1 PM to 2 PM IST\n",
    "allowed_start = datetime.strptime(\"13:00\", \"%H:%M\").time()\n",
    "allowed_end = datetime.strptime(\"14:00\", \"%H:%M\").time()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "id": "087f59b8-65f1-4b03-b92e-f3952cbfb5b7",
   "metadata": {},
   "outputs": [],
   "source": [
    "import tkinter as tk\n",
    "from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg\n",
    "from datetime import datetime, time"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "id": "c76a2b4f-1f6d-4efa-88f0-5555b527c4a6",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Apply filters\n",
    "filtered_df = apps_df[\n",
    "    (apps_df['Installs'] >= 10000) &\n",
    "    (apps_df['Revenue'] >= 10000) &\n",
    "    (apps_df['Android Ver'] > 4.0) &\n",
    "    (apps_df['Size'] > 15) &\n",
    "    (apps_df['Content Rating'] == 'Everyone') &\n",
    "    (apps_df['App Length'] <= 30)\n",
    "]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "id": "774e5647-243e-45c2-8538-c57365bc33b8",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Determine top 3 categories by number of apps after filtering\n",
    "top_categories = filtered_df['Category'].value_counts().nlargest(3).index.tolist()\n",
    "filtered_df = filtered_df[filtered_df['Category'].isin(top_categories)]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "id": "01dd98f4-fba2-46df-9256-1301835a37b9",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create root window\n",
    "root = tk.Tk()\n",
    "root.title(\"Time-Sensitive Chart\")\n",
    "\n",
    "# Time check: only allow chart between 1 PM and 2 PM IST\n",
    "india_time = datetime.now(pytz.timezone(\"Asia/Kolkata\")).time()\n",
    "allowed_start = time(13, 0)\n",
    "allowed_end = time(14, 0)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "99c7b8db-9e4e-404c-a3fe-80d03158312c",
   "metadata": {},
   "outputs": [],
   "source": [
    "if allowed_start <= india_time <= allowed_end:\n",
    "    # Group by Category and Type\n",
    "    group_data = filtered_df.groupby(['Category', 'Type']).agg({\n",
    "        'Installs': 'mean',\n",
    "        'Revenue': 'mean'\n",
    "    }).reset_index()\n",
    "\n",
    "    # Get top 3 categories by total installs\n",
    "    top3_categories = group_data.groupby('Category')['Installs'].sum().nlargest(3).index\n",
    "    group_data = group_data[group_data['Category'].isin(top3_categories)]\n",
    "\n",
    "    categories = sorted(group_data['Category'].unique())\n",
    "    bar_width = 0.35\n",
    "    index = list(range(len(categories)))\n",
    "\n",
    "    fig, ax1 = plt.subplots(figsize=(12, 7))\n",
    "    types = ['Free', 'Paid']\n",
    "    colors = {'Free': 'skyblue', 'Paid': 'orange'}\n",
    "\n",
    "    for i, t in enumerate(types):\n",
    "        data = group_data[group_data['Type'] == t]\n",
    "        data = data.set_index('Category').reindex(categories).reset_index()\n",
    "        \n",
    "        ax1.bar(\n",
    "            [x + i * bar_width for x in index],\n",
    "            data['Installs'].fillna(0),\n",
    "            width=bar_width,\n",
    "            label=f'Installs - {t}',\n",
    "            color=colors[t],\n",
    "            align='center'\n",
    "        )\n",
    "\n",
    "    ax2 = ax1.twinx()\n",
    "\n",
    "    for i, t in enumerate(types):\n",
    "        data = group_data[group_data['Type'] == t]\n",
    "        data = data.set_index('Category').reindex(categories).reset_index()\n",
    "        \n",
    "        ax2.plot(\n",
    "            [x + bar_width/2 for x in index],\n",
    "            data['Revenue'].fillna(0),\n",
    "            label=f'Revenue - {t}',\n",
    "            marker='o',\n",
    "            linestyle='--',\n",
    "            color=colors[t]\n",
    "        )\n",
    "\n",
    "    ax1.set_xlabel('App Categories')\n",
    "    ax1.set_ylabel('Average Installs')\n",
    "    ax2.set_ylabel('Average Revenue ($)')\n",
    "    ax1.set_title('Average Installs vs Revenue (Free vs Paid) in Top 3 Categories')\n",
    "    ax1.set_xticks([x + bar_width/2 for x in index])\n",
    "    ax1.set_xticklabels(categories)\n",
    "    ax1.legend(loc='upper left')\n",
    "    ax2.legend(loc='upper right')\n",
    "    ax1.grid(True, linestyle='--', alpha=0.5)\n",
    "\n",
    "    # Embed in Tkinter\n",
    "    canvas = FigureCanvasTkAgg(fig, master=root)\n",
    "    canvas.draw()\n",
    "    canvas.get_tk_widget().pack()\n",
    "\n",
    "else:\n",
    "    label = tk.Label(root, text=\"Chart not displayed. Allowed time is between 1 PM and 2 PM IST.\")\n",
    "    label.pack()\n",
    "\n",
    "root.mainloop()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "4c5ddf14-1b4b-4cbc-a8bb-5dcb8caebbe9",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
